name: example_client
description: Starting point for a Serverpod client.
version: 0.1.0
publish_to: none

resolution: workspace
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serverpod_client: 2.3.0
