name: jaspr
description: Experimental web framework that feels like Flutter but supports server-side rendering.
version: 0.2.0
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

executables:
  jaspr:

dependencies:
  args: ^2.3.0
  binary_codec: ^2.0.3
  hotreloader: ^3.0.4
  html: ^0.15.0
  http: ^0.13.4
  meta: ^1.7.0
  path: ^1.8.0
  shelf: ^1.2.0
  shelf_gzip: ^4.0.0
  shelf_proxy: ^1.0.1
  shelf_static: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.7
  build_web_compilers: ^3.2.2
  jaspr_test: ^0.1.0
  lints: ^1.0.1
  webdev: ^2.7.7
