name: jaspr
description: Modern web framework for building websites in Dart that feels like Flutter but supports server-side rendering.
version: 0.16.3
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues
documentation: https://docs.page/schultek/jaspr
funding:
  - https://github.com/sponsors/schultek

topics:
  - jaspr
  - web
  - html
  - server

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  binary_codec: ^2.0.3
  hotreloader: ^4.1.0
  html: ^0.15.0
  http: '>=0.13.0 <2.0.0'
  meta: ^1.7.0
  path: ^1.8.0
  shelf: ^1.2.0
  shelf_gzip: ^4.0.0
  shelf_proxy: ^1.0.1
  shelf_static: ^1.1.0
  web: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  jaspr_test: '>=0.1.0 <1.0.0'
  lints: ^3.0.0
  test: ^1.25.8
