name: jaspr_router
description: A routing component for jaspr.
version: 0.2.4
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues

topics:
  - jaspr
  - web

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.8.1

dev_dependencies:
  jaspr_test: '>=0.1.0 <1.0.0'
  lints: ^2.1.0
  test: ^1.22.0
