name: jaspr_router
description: A routing component for jaspr.
version: 0.8.1
homepage: https://jaspr.site
repository: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues
documentation: https://docs.jaspr.site/concepts/routing
funding:
  - https://github.com/sponsors/schultek

topics:
  - jaspr
  - web

environment:
  sdk: '>=3.8.0 <4.0.0'

resolution: workspace

dependencies:
  jaspr: ^0.22.0
  web: ^1.0.0

dev_dependencies:
  jaspr_test: '>=0.1.0 <1.0.0'
  test: ^1.22.0
