name: backend_shelf
description: An example of using a custom shelf server with jaspr.
version: 0.1.10-beta.0
publish_to: none

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  jaspr: ^0.22.0-beta.0
  shelf: ^1.3.1
  shelf_router: ^1.1.3

dev_dependencies:
  build_runner: ^2.6.0
  build_web_compilers: ^4.2.0
  jaspr_builder: ^0.22.0-beta.0
  jaspr_repo: any

jaspr:
  mode: server
