name: backend_shelf
description: An example of using a custom shelf server with jaspr.
version: 0.1.8
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'

resolution: workspace

dependencies:
  jaspr: ^0.21.0-dev.0
  shelf: ^1.3.1
  shelf_router: ^1.1.3

dev_dependencies:
  build_runner: ^2.6.0
  build_web_compilers: ^4.2.0
  jaspr_builder: ^0.21.0-dev.0
  jaspr_repo: any

jaspr:
  mode: server
