name: {{name}}
description: {{description}}
version: 0.0.1

environment:
  sdk: ^3.10.0

dependencies:
  jaspr: ^{{jasprCoreVersion}}
  jaspr_content: ^{{jasprContentVersion}}
  jaspr_router: ^{{jasprRouterVersion}}

dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^{{webCompilersVersion}}
  jaspr_builder: ^{{jasprBuilderVersion}}
  lints: ^5.0.0

jaspr:
  mode: static
