name: jaspr_cli
description: A command line interface to create, serve and build jaspr applications.
version: 0.18.2
homepage: https://jaspr.site
issue_tracker: https://github.com/schultek/jaspr/issues
documentation: https://docs.jaspr.site
funding:
  - https://github.com/sponsors/schultek

topics:
  - jaspr
  - web
  - cli

environment:
  sdk: '>=3.6.0 <4.0.0'

executables:
  jaspr:

dependencies:
  ansi_styles: ^0.3.2
  args: ^2.3.0
  cli_completion: ^0.5.0
  cli_util: ^0.4.0
  collection: ^1.17.1
  http: ^1.0.0
  io: ^1.0.4
  logging: ^1.1.1
  mason: ^0.1.0
  meta: ^1.7.0
  path: ^1.8.0
  pub_updater: ^0.5.0
  yaml: ^3.1.0
  # The following packages don't adhere to semantic versioning and might ship breaking changes in minor versions.
  # Therefore, we depend on fixed versions of these packages.
  build_daemon: 4.0.4
  dwds: 24.3.5
  webdev: 3.7.1
  shelf: ^1.4.1
  shelf_proxy: ^1.0.4
  async: ^2.13.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.22.0
