name: jaspr_cli
description: A command line interface to create, serve and build jaspr applications.
version: 0.5.0
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues
documentation: https://docs.page/schultek/jaspr
funding:
  - https://github.com/sponsors/schultek

topics:
  - jaspr
  - web
  - cli

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  jaspr:

dependencies:
  ansi_styles: ^0.3.2
  args: ^2.3.0
  build_daemon: ^4.0.0
  cli_completion: ^0.3.0
  cli_util: ^0.4.0
  collection: ^1.17.1
  dwds: ^19.0.0
  logging: ^1.1.1
  mason: ^0.1.0-dev.31
  meta: ^1.7.0
  path: ^1.8.0
  webdev: ^3.0.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.22.0
