name: clienttest
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: '>=3.8.0 <4.0.0'

resolution: workspace

dependencies:
  jaspr: ^0.21.7
  jaspr_router: ^0.8.0

dev_dependencies:
  build_runner: ^2.10.2
  build_web_compilers: ^4.4.2
  jaspr_builder: ^0.21.7
  jaspr_lints: ^0.5.1
  lints: ^5.0.0

jaspr:
  mode: static

