name: starter
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.10.0
  jaspr_router: ^0.3.1
  flutter:
    sdk: flutter
  jaspr_flutter_embed: any

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.0.7+1
  jaspr_builder: ^0.10.0
  lints: ^3.0.0

jaspr:
  mode: server

flutter:
  uses-material-design: true
