name: package_riverpod
description: An example showing how to use riverpod with jaspr.
version: 0.1.11
publish_to: none

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  jaspr: ^0.22.0
  jaspr_riverpod: ^0.4.0

dev_dependencies:
  build_runner: ^2.6.0
  build_web_compilers: ^4.2.0
  jaspr_builder: ^0.22.0

jaspr:
  mode: server
