name: package_riverpod
description: An example showing how to use riverpod with jaspr.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.9.0
  jaspr_riverpod: ^0.3.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  jaspr_builder: ^0.9.0
  lints: ^2.1.0

jaspr:
  mode: server
