name: jaspr_pad
description: Dartpad inspired online-editor for jaspr built with jaspr.
version: 0.1.0
publish_to: none
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analysis_server_lib: ^0.2.5
  archive: ^3.4.10
  codemirror: ^0.7.11+5.65.13
  collection: ^1.18.0
  dart_mappable: ^4.2.0
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  http: ^1.1.2
  jaspr: ^0.9.0
  jaspr_riverpod: ^0.3.8
  js: ^0.6.5
  markdown: ^7.1.1
  mdc_web: ^0.6.0
  path: ^1.9.0
  shelf: ^1.4.1
  shelf_router: ^1.1.2
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  dart_mappable_builder: ^4.2.0
  jaspr_builder: ^0.9.0
  jaspr_test: ^0.9.0
  lints: ^3.0.0
  test: ^1.25.0
  yaml_writer: ^1.0.1

jaspr:
  mode: server
