name: jaspr_serverpod
description: Serverpod integration for jaspr.
version: 0.5.3
homepage: https://jaspr.site
issue_tracker: https://github.com/schultek/jaspr/issues
documentation: https://docs.jaspr.site
funding:
  - https://github.com/sponsors/schultek

topics:
  - jaspr
  - web
  - serverpod

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  jaspr: ^0.18.0
  serverpod: '>=2.3.0 <2.5.0'
  serverpod_client: '>=2.3.0 <2.5.0'
  shelf: ^1.4.0
  web: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
