name: jaspr_content
description: Jaspr plugin for content driven sites.
version: 0.1.0
homepage: https://jaspr.site
issue_tracker: https://github.com/schultek/jaspr/issues
documentation: https://docs.jaspr.site
funding:
  - https://github.com/sponsors/schultek

topics:
  - jaspr
  - web
  - html
  - markdown

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  fbh_front_matter: ^0.0.1
  html: ^0.15.5
  http: ^1.3.0
  jaspr: ^0.18.0
  jaspr_router: ^0.6.3
  liquid_engine: ^0.2.2
  markdown: ^7.3.0
  mustache_template: ^2.0.0
  syntax_highlight_lite: ^0.0.1
  universal_web: ^1.1.0+2
  watcher: ^1.1.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

dependency_overrides:
  # Needed until https://github.com/jonahwilliams/mustache/pull/6 is merged.
  mustache_template:
    git:
      url: https://github.com/Rodsevich/mustache
      ref: 119cd0799e9c7b55397521ace7ca73787a32ef8d

screenshots:
  - description: The jaspr_content logo
    path: screenshots/logo.png
