name: dart_quotes_server
description: Collection of Dart quotes.
version: 0.1.8-dev.0
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  dart_quotes_client:
    path: ./client
  jaspr: ^0.21.0-dev.0
  jaspr_router: ^0.7.1
  jaspr_serverpod: ^0.5.6
  serverpod: 2.3.0
  serverpod_auth_google_flutter: 2.3.0
  serverpod_auth_server: 2.3.0
  serverpod_auth_shared_flutter: 2.3.0
  serverpod_serialization: 2.3.0

dev_dependencies:
  build_runner: ^2.6.0
  jaspr_web_compilers: ^4.2.0
  jaspr_builder: ^0.21.0-dev.0
  jaspr_lints: #^0.4.0
    path: ../../packages/jaspr_lints
  lints: ^5.0.0

jaspr:
  mode: server
  dev-command: dart bin/main.dart --apply-migrations
