name: jaspr_flutter_embed
description: Flutter element embedding bindings for jaspr.
version: 0.1.2
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues
documentation: https://docs.page/schultek/jaspr
funding:
  - https://github.com/sponsors/schultek

topics:
  - jaspr
  - web

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  jaspr: ^0.8.0
  js: ^0.6.5

dev_dependencies:
  lints: ^2.1.0
