name: jaspr_flutter_embed
description: Flutter element embedding bindings for jaspr.
version: 0.4.2
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues
documentation: https://docs.page/schultek/jaspr
funding:
  - https://github.com/sponsors/schultek

topics:
  - jaspr
  - web

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  jaspr: ^0.16.2
  web: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
