name: jaspr_flutter_embed
description: Flutter element embedding bindings for jaspr.
version: 0.4.6
homepage: https://jaspr.site
issue_tracker: https://github.com/schultek/jaspr/issues
documentation: https://docs.jaspr.site
funding:
  - https://github.com/sponsors/schultek

topics:
  - jaspr
  - web

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.24.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  jaspr: ^0.19.0
  web: ^1.0.0

dev_dependencies:
  lints: ^5.1.1
