name: jaspr_lints
description: A collection of lints and assists for jaspr projects.
version: 0.5.0-dev.0
homepage: https://jaspr.site
repository: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues
documentation: https://docs.jaspr.site/get_started/linting
funding:
  - https://github.com/sponsors/schultek

topics:
  - jaspr
  - web
  - lints

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  analyzer: ^8.0.0
  analyzer_plugin: ^0.13.4
  custom_lint_builder: ^0.8.1
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^5.0.0
