name: jaspr_lints
description: A collection of lints and assists for jaspr projects.
version: 0.2.1
homepage: https://jaspr.site
issue_tracker: https://github.com/schultek/jaspr/issues
documentation: https://docs.jaspr.site/get_started/linting
funding:
  - https://github.com/sponsors/schultek

topics:
  - jaspr
  - web
  - lints

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  analyzer: ^6.6.0
  analyzer_plugin: ^0.11.0
  custom_lint_builder: ^0.7.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^4.0.0
