name: flutter_plugin_interop
description: A pure client-side app without ssr.
version: 0.1.10-beta.0
publish_to: none

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  cloud_firestore: ^5.4.1
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  jaspr: ^0.22.0-beta.0
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.6.0
  jaspr_builder: ^0.22.0-beta.0
  jaspr_web_compilers: ^4.2.0

jaspr:
  mode: server
