name: flutter_plugin_interop
description: A pure client-side app without ssr.
version: 0.1.3
publish_to: none

resolution: workspace
environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  jaspr: ^0.16.0
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  cloud_firestore: ^5.4.1
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_builder: ^0.16.3
  jaspr_web_compilers: ^4.0.10
  lints: ^4.0.0

jaspr:
  mode: server
