name: flutter_plugin_interop
description: A pure client-side app without ssr.
version: 0.1.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.14.0
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_builder: ^0.14.0
  jaspr_web_compilers: ^4.0.10
  lints: ^4.0.0

jaspr:
  mode: server
