name: flutter_plugin_interop
description: A pure client-side app without ssr.
version: 0.1.6
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  jaspr: ^0.19.0
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  cloud_firestore: ^5.4.1
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_builder: ^0.19.1
  jaspr_web_compilers: ^4.1.0
  jaspr_lints: ^0.4.0
  lints: ^5.0.0

jaspr:
  mode: server
