name: {{project_name}}
description: {{project_description}}
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  jaspr: ^0.2.0
  jaspr_riverpod: ^0.1.0-dev.1

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^1.0.0
  webdev: 2.7.7