name: {{project_name}}
description: {{project_description}}
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.10.0
  jaspr_riverpod: ^0.3.9

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.1.0

jaspr:
  mode: client
