name: dart_quotes
description: A collection of Dart quotes. Built for FullStackFlutter Conference.
version: 0.1.10
publish_to: none

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  cloud_firestore: ^5.4.1
  dart_firebase_admin: ^0.4.1
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  jaspr: ^0.21.0
  jaspr_router: ^0.8.0

dev_dependencies:
  build_runner: ^2.6.0
  jaspr_builder: ^0.21.0
  jaspr_repo: any
  jaspr_web_compilers: ^4.2.0

jaspr:
  mode: server
