name: dart_quotes
description: A collection of Dart quotes. Built for FullStackFlutter Conference.
version: 0.1.3
publish_to: none

resolution: workspace
environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  firebase_core: ^3.4.1
  jaspr: ^0.16.0
  jaspr_router: ^0.6.0
  cloud_firestore: ^5.4.1
  dart_firebase_admin: ^0.3.1
  firebase_auth: ^5.2.1

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.0.10
  jaspr_builder: ^0.16.3
  lints: ^4.0.0

jaspr:
  mode: server

