name: dart_quotes
description: A collection of Dart quotes. Built for FullStackFlutter Conference.
version: 0.1.7
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  firebase_core: ^3.4.1
  jaspr: ^0.20.0
  jaspr_router: ^0.7.1
  cloud_firestore: ^5.4.1
  dart_firebase_admin: ^0.4.1
  firebase_auth: ^5.2.1

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.1.0
  jaspr_builder: ^0.19.1
  jaspr_lints: ^0.4.0
  lints: ^5.0.0

jaspr:
  mode: server

