name: backend_dart_frog
description: An example application built with dart_frog & jaspr.
version: 0.1.9
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'

resolution: workspace

dependencies:
  dart_frog: ^1.0.0
  jaspr: ^0.21.0
  shelf: ^1.4.2

dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^4.2.0
  jaspr_builder: ^0.21.0
  jaspr_repo: any

dependency_overrides:
  hotreloader: ^4.1.0

jaspr:
  mode: server
