name: fluttercon
description: A new jaspr project.
version: 0.0.11
publish_to: none
homepage: https://fluttercon.schultek.de
issue_tracker: https://github.com/schultek/jaspr/issues

environment:
  sdk: '>=3.8.0 <4.0.0'

resolution: workspace

dependencies:
  collection: ^1.18.0
  dart_mappable: ^4.2.2
  http: ^1.2.1
  intl: ^0.20.0
  jaspr: ^0.21.0
  jaspr_router: ^0.8.0
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.6.0
  dart_mappable_builder: ^4.2.3
  jaspr_builder: ^0.21.0
  jaspr_repo: any
  jaspr_web_compilers: ^4.2.0

jaspr:
  mode: static

