name: fluttercon
description: A new jaspr project.
version: 0.0.3
publish_to: none
homepage: https://fluttercon.schultek.de
issue_tracker: https://github.com/schultek/jaspr/issues

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  dart_mappable: ^4.2.2
  http: ^1.2.1
  intl: ^0.19.0
  jaspr: ^0.15.1
  jaspr_router: ^0.5.1
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.0
  dart_mappable_builder: ^4.2.3
  jaspr_web_compilers: ^4.0.10
  jaspr_builder: ^0.15.1
  lints: ^4.0.0

jaspr:
  mode: static

