name: enginetest
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  jaspr: ^0.22.2
  jaspr_flutter_embed:
    path: ../../packages/jaspr_flutter_embed
  package_info_plus: ^9.0.0

dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^4.4.9
  jaspr_builder: ^0.22.2
  lints: ^5.0.0

jaspr:
  mode: client
  flutter: embedded
