name: {{name}}
description: A purely server-side rendered app without client hydration.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^{{jasprCoreVersion}}

dev_dependencies:
  build_runner: ^2.4.0
  {{webCompilersPackage}}: ^{{webCompilersVersion}}
  jaspr_builder: ^{{jasprBuilderVersion}}
  lints: ^2.1.0

jaspr:
  uses-ssr: true
