name: server_dart_frog
description: An example application built with dart_frog & jaspr.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^0.2.0
  jaspr: ^0.9.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  jaspr_builder: ^0.9.0
  lints: ^2.1.0

dependency_overrides:
  hotreloader: ^4.1.0

