name: flutter_multi_view
description: A new jaspr project.
version: 0.0.9-beta.0
publish_to: none

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  jaspr: ^0.22.0-beta.0
  jaspr_flutter_embed: ^0.4.7

dev_dependencies:
  build_runner: ^2.6.0
  flutter_test:
    sdk: flutter
  jaspr_builder: ^0.22.0-beta.0
  jaspr_web_compilers: ^4.2.0

jaspr:
  mode: static

flutter:
  uses-material-design: true
