name: flutter_multi_view
description: A new jaspr project.
version: 0.0.7-dev.1
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  jaspr: ^0.21.0-dev.0
  jaspr_flutter_embed: ^0.4.7

dev_dependencies:
  build_runner: ^2.6.0
  jaspr_web_compilers: ^4.2.0
  jaspr_builder: ^0.21.0-dev.0
  jaspr_lints: #^0.4.0
    path: ../../packages/jaspr_lints
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

jaspr:
  mode: static

flutter:
  uses-material-design: true
