name: jaspr_test
description: Testing utilities for jaspr.
version: 0.22.2
homepage: https://jaspr.site
repository: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues
documentation: https://docs.jaspr.site/dev/testing
funding:
  - https://github.com/sponsors/schultek

topics:
  - jaspr
  - web
  - testing

environment:
  sdk: ">=3.8.0 <4.0.0"

resolution: workspace

dependencies:
  html: ^0.15.0
  http: ">=0.13.0 <2.0.0"
  jaspr: 0.22.2
  meta: ^1.7.0
  test: ^1.22.0
  universal_web: ^1.1.0+1
