name: jaspr_test
description: Testing utilities for jaspr.
version: 0.20.0
homepage: https://jaspr.site
repository: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues
documentation: https://docs.jaspr.site/concepts/testing
funding:
  - https://github.com/sponsors/schultek

topics:
  - jaspr
  - web
  - testing

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  html: ^0.15.0
  http: '>=0.13.0 <2.0.0'
  jaspr: ^0.20.0
  meta: ^1.7.0
  test: ^1.22.0
  universal_web: ^1.1.0+1

dev_dependencies:
  lints: ^5.0.0
