name: example_server
description: Starting point for a Serverpod server.
version: 0.1.5
publish_to: none

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  jaspr: ^0.22.0
  jaspr_serverpod: ^0.6.0
  serverpod: 2.3.0

dev_dependencies:
  build_runner: ^2.6.0
  build_web_compilers: ^4.2.0
  jaspr_builder: ^0.22.0

jaspr:
  mode: server
  port: 8082
