name: dart_quotes_client
description: Generated client for dart_quotes serverpod app.

resolution: workspace
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  serverpod_auth_client: 2.3.0
  serverpod_client: 2.3.0
