name: website
description: The Jaspr website hosted at https://jaspr.site
version: 0.1.6
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

dependencies:
  highlight: ^0.7.0
  http: ^1.3.0
  jaspr: ^0.22.0
  jaspr_content: ^0.4.5
  jaspr_router: ^0.8.0
  lukehog_client: ^0.4.6
  markdown: ^7.3.0
  universal_web: ^1.1.0+2

dev_dependencies:
  build_runner: ^2.6.0
  build_web_compilers: ^4.4.6
  jaspr_builder: ^0.22.0

jaspr:
  mode: static
  flutter: plugins
