name: website
description: The Jaspr website hosted at https://jaspr.site
version: 0.1.2
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'

resolution: workspace

dependencies:
  highlight: ^0.7.0
  http: ^1.3.0
  jaspr: ^0.21.0-dev.0
  jaspr_router: ^0.7.1
  lukehog_client: ^0.4.6
  markdown: ^7.3.0
  universal_web: ^1.1.0+2

dev_dependencies:
  build_runner: ^2.6.0
  jaspr_builder: ^0.21.0-dev.0
  jaspr_repo: any
  jaspr_web_compilers: ^4.2.3+1

jaspr:
  mode: static
