name: {{name}}
description: {{description}}
version: 0.0.1

environment:
  sdk: ^3.10.0

dependencies:{{#flutter}}
  flutter:
     sdk: flutter{{/flutter}}
  jaspr: ^{{jasprCoreVersion}}{{#flutter}}
  jaspr_flutter_embed: ^{{jasprFlutterEmbedVersion}}{{/flutter}}{{#routing}}
  jaspr_router: ^{{jasprRouterVersion}}{{/routing}}{{#shelf}}
  shelf: ^1.4.0
  shelf_router: ^1.1.0{{/shelf}}

dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^{{webCompilersVersion}}{{#flutter}}
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter{{/flutter}}
  jaspr_builder: ^{{jasprBuilderVersion}}{{^flutter}}
  lints: ^5.0.0{{/flutter}}

jaspr:
  mode: {{mode}}{{#plugins}}
  flutter: plugins{{/plugins}}{{#flutter}}
  flutter: embedded

flutter:
  uses-material-design: true{{/flutter}}
