name: jaspr_riverpod
description: Riverpod for Jaspr
version: 0.3.16
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues

topics:
  - jaspr
  - web

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.16.2
  meta: ^1.9.1
  riverpod: ^2.6.0

dev_dependencies:
  jaspr_test: '>=0.1.0 <1.0.0'
  lints: ^4.0.0
  test: ^1.24.1
