name: jaspr_riverpod
description: Riverpod for Jaspr
version: 0.4.4
homepage: https://github.com/schultek/jaspr
repository: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues
funding:
  - https://github.com/sponsors/schultek

topics:
  - jaspr
  - web

environment:
  sdk: ">=3.8.0 <4.0.0"

resolution: workspace

dependencies:
  jaspr: ^0.22.0
  meta: ^1.9.1
  riverpod: ^3.0.2

dev_dependencies:
  jaspr_test: ">=0.1.0 <1.0.0"
  test: ^1.24.1
  web: ^1.1.1
