name: jaspr_builder
description: Builders for jaspr
version: 0.3.0
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: ^5.4.0
  build: ^2.0.0
  collection: ^1.15.0
  dart_style: ^2.2.3
  glob: ^2.1.1
  jaspr: ^0.3.0
  path: ^1.8.0
  source_gen: ^1.2.0

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^2.0.1
  test: ^1.21.0
